---
substitutions:
  name: weactstudio-esp32c3-core

esphome:
  name: ${name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
  variant: esp32c3

logger:
  hardware_uart: USB_SERIAL_JTAG
