---
packages:
  board: !include ../boards/weactstudio-esp32c3-core.yaml

substitutions:
  name: esp32c3-core-bt-proxy
  wifi_ap_password: ""

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"
  on_boot:
    then:
      - wait_until:
          condition:
            wifi.connected:
      - lambda: >
            id(ble_tracker).set_scan_continuous(true);
            id(ble_tracker).start_scan();

api:

ota:

wifi:
  ap:
    password: ${wifi_ap_password}

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    continuous: false

bluetooth_proxy:
  active: true
