---
packages:
  board: !include ../boards/weactstudio-esp32s3-core.yaml

substitutions:
  name: esp32s3-core-bt-proxy
  wifi_ap_password: ""

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"

api:

ota:

wifi:
  ap:
    password: ${wifi_ap_password}

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

bluetooth_proxy:
  active: true
